# NumPy

NumPy is the work-horse of numerical and scientific computations in python. Its the de-fact and go to library for modern ML/DL tasks.

We will discuss basic and most essential numpy operations/usage for ML tasks and model building

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


## Creating ndarray

In [6]:
# 'ndarray' (n-dimentional array) is the most fundamental data-structure in numpy
arr = np.array([1, 2, 3, 4, 5]) # Created using a pythin list of int
print(arr)
print(type(arr))  
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [11]:
# As shown above the numpy arrays are of type `ndarray` 
# requires its elements to be of same data-type (int64) above
# if we try mix data-types then it'd 'upcast' the datatype
# Created using a pythin list of mix type but all converted to string 
arr = np.array([1, 2, 'hello', 4.0, 5]) 
print(arr)
print(arr.dtype)

['1' '2' 'hello' '4.0' '5']
<U21


In [13]:
# another example of upcast
arr = np.array([1, 2, 3, 4.0, 5]) # All int except one float
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [12]:
# explicitly set the data type of the resulting array,
arr = np.array([1, 2, 3, 4, 5], dtype='float32') # Created using a pythin list with explit type as float
print(arr)
print(type(arr))  
print(arr.dtype)

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float32


In [16]:
# A nested list would create multi-dimentional array
md_arr = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(md_arr)
print(md_arr.ndim)  # dimention 
print(md_arr.shape) # number of elements (size) in each dimention of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [17]:
# quik zero intialised array of desired shape
z_arr = np.zeros(10, dtype=int)
print(z_arr)

[0 0 0 0 0 0 0 0 0 0]


In [20]:
# quik one intialised array of desired shape
o_arr = np.ones((5, 2), dtype=int)
print(o_arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
